### ISSUE TITLE
[Question] Once you support a new version of Beat Saber, does it still work on the older versions?

### ISSUE THREAD

**Issue by phazei** [raineio/Lapiz#67]
I noticed v0.2.7 added support for 1.36.  I'm going to be running 1.35 for a long while since that's the one most of the mods have chosen to support.  So I was just wondering, will versions > 0.2.6 still be ok to install for greater stability in 1.35?  And if not, will bug fixes still be made for the v1.35?
Thanks for all your work making this mod for the community!

**Comment by raineio** [comment]
Versions are only supporting the versions they are released for. You would need an older Lapiz for 1.35.
